name: Test All Case

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cases:
          [
            "0000",
            "0001",
            "0002",
            "0003",
            "0004",
            "0005",
            "0006",
            "0007",
            "0008",
            "0009",
            "0010",
            "0011",
            "0012",
            "0013",
            "0014",
            "0015",
            "0016",
            "0017",
            "0018",
            "0019",
            "0020",
            "0021",
            "0022",
            "0023",
            "0024",
            "0025",
            "0026",
            "0027",
            "0028",
            "0029",
            "0030",
            "0031",
            "0032",
            "0033",
            "0034",
            "0035",
            "0036",
            "0037",
            "0038",
            "0039",
            "0040",
            "0041",
            "0042",
            "0043",
            "0044",
            "0045",
            "0046",
            "0047",
            "0048",
            "0049",
            "0050",
            "0051",
            "0052",
            "0053",
            "0054",
            "0055",
            "0056",
            "0057",
            "0058",
            "0059",
            "0060",
            "0061",
            "0062",
            "0063",
            "0064",
            "0065",
            "0066",
            "0067",
            "0068",
            "0069",
            "0070",
            "0071",
            "0072",
            "0073",
            "0074",
            "0075",
            "0076",
            "0078",
            "0079",
            "0080",
            "0081",
            "0082",
            "0083",
            "0084",
            "0085",
            "0086",
            "0087",
            "0088",
            "0089",
            "0090",
            "0091",
            "0092",
            "0093",
            "0094",
            "0095",
            "0096",
            "0097",
            "0098",
            "0099",
            "0100",
            "0101",
            "0102",
            "0103",
            "0104",
            "0105",
            "0106",
            "0107",
            "0108",
            "0109",
            "0110",
            "0111",
            "0112",
            "0113",
            "0114",
            "0115",
            "0116",
            "0117",
            "0118",
            "0119",
            "0120",
            "0121",
            "0122",
            "0123",
            "0124",
            "0125",
            "0126",
            "0127",
            "0128",
            "0129",
            "0130",
            "0131",
            "0132",
            "0133",
            "0134",
            "0135",
            "0136",
            "0137",
            "0138",
            "0139",
            "0140",
            "0141",
            "0142",
            "0143",
            "0144",
            "0145",
            "0146",
            "0147",
            "0148",
            "0149",
            "0150",
            "0151",
            "0152",
            "0153",
            "0154",
            "0155",
            "0156",
            "0157",
            "0158",
            "0159",
            "0160",
            "0161",
            "0162",
            "0163",
            "0164",
            "0165",
            "0166",
            "0167",
            "0168",
            "0169",
            "0170",
            "0171",
            "0172",
            "0173",
            "0174",
            "0175",
            "0176",
            "0178",
            "0179",
            "0180",
            "0181",
            "0182",
            "0183",
            "0184",
            "0185",
            "0186",
            "0187",
            "0188",
            "0189",
            "0190",
            "0191",
            "0192",
            "0193",
            "0194",
            "0195",
            "0196",
            "0197",
            "0198",
            "0199",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./tools/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Build cpp solver
        run: g++ ./cpp/est_greedy.cpp
      - name: Run tests
        # run: cargo run --manifest-path ./tools/Cargo.toml --release --bin tester ./a.out < ./tools/in/${{matrix.cases}}.txt > ./out.txt
        run: cargo run --manifest-path ./tools/Cargo.toml --release --bin tester go run ./cmd/best.go < ./tools/in/${{matrix.cases}}.txt > ./out.txt
      - name: set-output
        run: echo "::set-output name=SCORE::`cat ./score.txt`"
        id: score
      - name: set-output2
        run: echo "::set-output name=EST_SCORE::`cat ./estscore.txt`"
        id: est-score
      - uses: actions/upload-artifact@v2
        with:
          name: score-${{matrix.cases}}-${{steps.score.outputs.SCORE}}-${{steps.est-score.outputs.EST_SCORE}}
          path: ./score.txt
      - uses: actions/upload-artifact@v2
        with:
          name: estscore-${{matrix.cases}}
          path: ./estscore.txt
  check-result:
    runs-on: ubuntu-latest
    needs: [run-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: all-result
      - name: calc all score
        run: find ./all-result -type f -name "score.txt" | xargs cat | awk '{s += $1} END {print s}' > all_score.txt
      - name: calc all est-score
        run: find ./all-result -type f -name "estscore.txt" | xargs cat | awk '{s += $1} END {print s}' > all_estscore.txt
      - name: set-output
        run: echo "::set-output name=ALL_SCORE::`cat ./all_score.txt`"
        id: all-score
      - name: set-output2
        run: echo "::set-output name=ALL_EST_SCORE::`cat ./all_estscore.txt`"
        id: all-estscore
      - uses: actions/upload-artifact@v2
        with:
          name: allscore-${{steps.all-score.outputs.ALL_SCORE}}
          path: ./all_score.txt
      - uses: actions/upload-artifact@v2
        with:
          name: allscore-${{steps.all-estscore.outputs.ALL_EST_SCORE}}
          path: ./all_estscore.txt
