name: Test All Case

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cases:
          [
            "0000",
            "0001",
            "0002",
            "0003",
            "0004",
            "0005",
            "0006",
            "0007",
            "0008",
            "0009",
            "0010",
            "0011",
            "0012",
            "0013",
            "0014",
            "0015",
            "0016",
            "0017",
            "0018",
            "0019",
            "0020",
            "0021",
            "0022",
            "0023",
            "0024",
            "0025",
            "0026",
            "0027",
            "0028",
            "0029",
            "0030",
            "0031",
            "0032",
            "0033",
            "0034",
            "0035",
            "0036",
            "0037",
            "0038",
            "0039",
            "0040",
            "0041",
            "0042",
            "0043",
            "0044",
            "0045",
            "0046",
            "0047",
            "0048",
            "0049",
          ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./tools/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: cargo run --manifest-path ./tools/Cargo.toml --release --bin tester go run ./cmd/rank_est_stop.go < ./tools/in/${{matrix.cases}}.txt > ./out.txt
      - name: set-output
        run: echo "::set-output name=SCORE::`cat ./score.txt`"
        id: score
      - uses: actions/upload-artifact@v2
        with:
          name: score-${{matrix.cases}}-${{steps.score.outputs.SCORE}}
          path: ./score.txt
  check-result:
    runs-on: ubuntu-latest
    needs: [run-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: all-result
      - name: calc all score
        run: find ./all-result -type f | grep ".txt" | xargs cat | awk '{s += $1} END {print s}' > all_score.txt
      - name: set-output
        run: echo "::set-output name=ALL_SCORE::`cat ./all_score.txt`"
        id: all-score
      - uses: actions/upload-artifact@v2
        with:
          name: allscore-${{steps.all-score.outputs.ALL_SCORE}}
          path: ./all_score.txt
      - name: show all score
        run: cat ./all_score.txt
