name: Test All Case

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cases: ["0000", "0001", "0002"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./tools/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: cargo run --manifest-path ./tools/Cargo.toml --release --bin tester go run ./cmd/rank_est.go < ./tools/in/${{matrix.cases}}.txt > ./out.txt
