name: Test All Case

on:
  push:
    branches: [main]

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions-rs/cargo@v1
        with:
          command: run
          args: --manifest-path ./tools/Cargo.toml --release --bin tester go run ./cmd/rank_est.go < ./tools/in/0001.txt > out.txt
