name: Test All Case

on:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  run-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cases: ["0000", "0001"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ./tools/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: cargo run --manifest-path ./tools/Cargo.toml --release --bin tester go run ./cmd/rank_est.go < ./tools/in/${{matrix.cases}}.txt > ./out.txt
      - name: ls
        run: ls
      - uses: actions/upload-artifact@v2
        with:
          name: score-${{matrix.cases}}
          path: ./score.txt
  check-result:
    runs-on: ubuntu-latest
    needs: [run-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: all-result
      - name: Show result
        run: find ./all-result -type f | grep ".txt" | xargs cat | awk '{s += $1} END {print s}'
